In [1]:
import numpy as np
import pandas as pd

In [2]:
registry = pd.read_excel("datasets/Registry.xlsx", nrows=20000)

/usr/lib/python3.13/site-packages/openpyxl/styles/stylesheet.py:226: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

In [3]:
registry.head(5)

,Единый реестр субъектов малого и среднего предпринимательства по состоянию на 15.04.2024,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21,Unnamed: 22
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,№ п/п,Наименование / ФИО,Тип субъекта,Категория,ОГРН,ИНН,Основной вид деятельности,Регион,Район,Город,...,Дата исключения из реестра,Телефон,E-mail,WWW,Наличие лицензий,"Наличие заключенных договоров, контрактов","Производство инновационной, высокотехнологично...",Участие в программах партнерства,Является социальным предприятием,Среднесписочная численность работников за пред...
2,1,""" МЕГАПОЛИС "" ОБЩЕСТВО С ОГРАНИЧЕННОЙ ОТВЕТСТВ...",Юридическое лицо,Не является субъектом МСП,1027800523376,7801190028,41.2 Строительство жилых и нежилых зданий,78 - г.Санкт-Петербург,NaN,NaN,...,10.10.2021,NaN,NaN,NaN,Нет,Нет,Нет,Нет,Нет,NaN
3,2,""" СТАЛЬИНВЕСТСТРОЙ "" ОБЩЕСТВО С ОГРАНИЧЕННОЙ О...",Юридическое лицо,Не является субъектом МСП,1037800033545,7801227976,41.20 Строительство жилых и нежилых зданий,78 - г.Санкт-Петербург,NaN,NaN,...,10.08.2018,NaN,NaN,NaN,Нет,Нет,Нет,Нет,Нет,NaN
4,3,""" СТРОЙТЕХНИКА - М "" ОБЩЕСТВО С ОГРАНИЧЕННОЙ О...",Юридическое лицо,Не является субъектом МСП,1025204418293,5263039399,41.20 Строительство жилых и нежилых зданий,52 - Нижегородская область,NaN,г Нижний Новгород,...,10.07.2022,NaN,NaN,NaN,Нет,Нет,Нет,Нет,Нет,NaN

In [4]:
# удаляем 1-ый столбец:
registry.drop(columns="Единый реестр субъектов малого и среднего предпринимательства по состоянию на 15.04.2024", inplace=True)
# удаляем 1-ую строку:
registry.drop(0, inplace=True)

In [5]:
registry.head(3)

,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,...,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21,Unnamed: 22
1,Наименование / ФИО,Тип субъекта,Категория,ОГРН,ИНН,Основной вид деятельности,Регион,Район,Город,Населенный пункт,...,Дата исключения из реестра,Телефон,E-mail,WWW,Наличие лицензий,"Наличие заключенных договоров, контрактов","Производство инновационной, высокотехнологично...",Участие в программах партнерства,Является социальным предприятием,Среднесписочная численность работников за пред...
2,""" МЕГАПОЛИС "" ОБЩЕСТВО С ОГРАНИЧЕННОЙ ОТВЕТСТВ...",Юридическое лицо,Не является субъектом МСП,1027800523376,7801190028,41.2 Строительство жилых и нежилых зданий,78 - г.Санкт-Петербург,NaN,NaN,NaN,...,10.10.2021,NaN,NaN,NaN,Нет,Нет,Нет,Нет,Нет,NaN
3,""" СТАЛЬИНВЕСТСТРОЙ "" ОБЩЕСТВО С ОГРАНИЧЕННОЙ О...",Юридическое лицо,Не является субъектом МСП,1037800033545,7801227976,41.20 Строительство жилых и нежилых зданий,78 - г.Санкт-Петербург,NaN,NaN,NaN,...,10.08.2018,NaN,NaN,NaN,Нет,Нет,Нет,Нет,Нет,NaN

In [6]:
# именуем столбцы
dic = {}
old = registry.keys()
new = registry.iloc[0].values
for i in range(len(old)): dic[old[i]] = new[i]
registry.rename(columns=dic, inplace=True)

#удаляем исходную строку с заголовками столбцов
registry = registry.drop(1).reset_index().drop(columns="index")

In [7]:
registry.head(3)

,Наименование / ФИО,Тип субъекта,Категория,ОГРН,ИНН,Основной вид деятельности,Регион,Район,Город,Населенный пункт,...,Дата исключения из реестра,Телефон,E-mail,WWW,Наличие лицензий,"Наличие заключенных договоров, контрактов","Производство инновационной, высокотехнологичной продукции",Участие в программах партнерства,Является социальным предприятием,Среднесписочная численность работников за предшествующий календарный год
0,""" МЕГАПОЛИС "" ОБЩЕСТВО С ОГРАНИЧЕННОЙ ОТВЕТСТВ...",Юридическое лицо,Не является субъектом МСП,1027800523376,7801190028,41.2 Строительство жилых и нежилых зданий,78 - г.Санкт-Петербург,NaN,NaN,NaN,...,10.10.2021,NaN,NaN,NaN,Нет,Нет,Нет,Нет,Нет,NaN
1,""" СТАЛЬИНВЕСТСТРОЙ "" ОБЩЕСТВО С ОГРАНИЧЕННОЙ О...",Юридическое лицо,Не является субъектом МСП,1037800033545,7801227976,41.20 Строительство жилых и нежилых зданий,78 - г.Санкт-Петербург,NaN,NaN,NaN,...,10.08.2018,NaN,NaN,NaN,Нет,Нет,Нет,Нет,Нет,NaN
2,""" СТРОЙТЕХНИКА - М "" ОБЩЕСТВО С ОГРАНИЧЕННОЙ О...",Юридическое лицо,Не является субъектом МСП,1025204418293,5263039399,41.20 Строительство жилых и нежилых зданий,52 - Нижегородская область,NaN,г Нижний Новгород,NaN,...,10.07.2022,NaN,NaN,NaN,Нет,Нет,Нет,Нет,Нет,NaN

In [8]:
registry.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19998 entries, 0 to 19997
Data columns (total 22 columns):
 #   Column                                                                    Non-Null Count  Dtype
---  ------                                                                    --------------  -----
 0   Наименование / ФИО                                                        19998 non-null  object
 1   Тип субъекта                                                              19998 non-null  object
 2   Категория                                                                 19998 non-null  object
 3   ОГРН                                                                      19998 non-null  object
 4   ИНН                                                                       19998 non-null  object
 5   Основной вид деятельности                                                 19998 non-null  object
 6   Регион                                                                    19998 non-null  object
 7   Район                                                                     7182 non-null   object
 8   Город                                                                     12402 non-null  object
 9   Населенный пункт                                                          6138 non-null   object
 10  Вновь созданный                                                           19998 non-null  object
 11  Дата включения в реестр                                                   19998 non-null  object
 12  Дата исключения из реестра                                                10570 non-null  object
 13  Телефон                                                                   46 non-null     object
 14  E-mail                                                                    46 non-null     object
 15  WWW                                                                       4 non-null      object
 16  Наличие лицензий                                                          19998 non-null  object
 17  Наличие заключенных договоров, контрактов                                 19998 non-null  object
 18  Производство инновационной, высокотехнологичной продукции                 19998 non-null  object
 19  Участие в программах партнерства                                          19998 non-null  object
 20  Является социальным предприятием                                          19998 non-null  object
 21  Среднесписочная численность работников за предшествующий календарный год  923 non-null    object
dtypes: object(22)
memory usage: 3.4+ MB

In [9]:
registry.describe()

,Наименование / ФИО,Тип субъекта,Категория,ОГРН,ИНН,Основной вид деятельности,Регион,Район,Город,Населенный пункт,...,Дата исключения из реестра,Телефон,E-mail,WWW,Наличие лицензий,"Наличие заключенных договоров, контрактов","Производство инновационной, высокотехнологичной продукции",Участие в программах партнерства,Является социальным предприятием,Среднесписочная численность работников за предшествующий календарный год
count,19998,19998,19998,19998,19998,19998,19998,7182,12402,6138,...,10570,46,46,4,19998,19998,19998,19998,19998,923
unique,18953,2,4,19998,19402,4,89,2484,1879,4875,...,92,44,44,4,2,1,1,1,2,126
top,БЕЛОВ АЛЕКСАНДР ВЛАДИМИРОВИЧ,Индивидуальный предприниматель,Не является субъектом МСП,320920000000926,545328555812,41.20 Строительство жилых и нежилых зданий,77 - г.Москва,АНАПСКИЙ РАЙОН,г Краснодар,СЕЛО ТОЛСТОЙ-ЮРТ,...,10.07.2023,+7(996)7838692,89216347654@mail.ru,http://www.strojsipavetisyan.com/,Нет,Нет,Нет,Нет,Нет,1
freq,7,18617,10570,1,7,18512,1418,43,165,13,...,746,2,2,1,19739,19998,19998,19998,19996,224

Удаляем ненужные колонки и колонки, состоящие только из одного значения (в таблице выше -- строка `unique`):

In [10]:
registry.drop(
    columns=[
        "Производство инновационной, высокотехнологичной продукции",
        "Дата исключения из реестра", "Вновь созданный",
        "Наличие заключенных договоров, контрактов",
        "Участие в программах партнерства", "ОГРН",
        "Район", "Телефон", "E-mail", "WWW",
        "Является социальным предприятием"
    ], inplace=True)

In [11]:
registry.sample(3)

,Наименование / ФИО,Тип субъекта,Категория,ИНН,Основной вид деятельности,Регион,Город,Населенный пункт,Дата включения в реестр,Наличие лицензий,Среднесписочная численность работников за предшествующий календарный год
10116,АНТОНОВ АНДРЕЙ ВЛАДИМИРОВИЧ,Индивидуальный предприниматель,Микропредприятие,280802690588,41.20 Строительство жилых и нежилых зданий,28 - Амурская область,ГОРОД ТЫНДА,NaN,01.08.2016,Нет,NaN
13963,АХМЕТОВ РУСЛАН РАФГАТОВИЧ,Индивидуальный предприниматель,Микропредприятие,781914021164,41.20 Строительство жилых и нежилых зданий,78 - г.Санкт-Петербург,г Петергоф,NaN,10.08.2021,Нет,NaN
15315,БАГЯН ВАЛЕРИК АРТЕМОВИЧ,Индивидуальный предприниматель,Не является субъектом МСП,366520973099,41.20 Строительство жилых и нежилых зданий,23 - Краснодарский край,г Новокубанск,NaN,10.07.2023,Нет,NaN

In [12]:
registry.describe()

,Наименование / ФИО,Тип субъекта,Категория,ИНН,Основной вид деятельности,Регион,Город,Населенный пункт,Дата включения в реестр,Наличие лицензий,Среднесписочная численность работников за предшествующий календарный год
count,19998,19998,19998,19998,19998,19998,12402,6138,19998,19998,923
unique,18953,2,4,19402,4,89,1879,4875,93,2,126
top,БЕЛОВ АЛЕКСАНДР ВЛАДИМИРОВИЧ,Индивидуальный предприниматель,Не является субъектом МСП,545328555812,41.20 Строительство жилых и нежилых зданий,77 - г.Москва,г Краснодар,СЕЛО ТОЛСТОЙ-ЮРТ,01.08.2016,Нет,1
freq,7,18617,10570,7,18512,1418,165,13,2367,19739,224

In [13]:
mask = (registry["Тип субъекта"] == "Юридическое лицо") \
    & (registry["Основной вид деятельности"] == "41.20 Строительство жилых и нежилых зданий") & (
        (registry["Категория"] == "Малое предприятие") | (registry["Категория"] == "Среднее предприятие")
)
registry = registry[mask].reset_index().drop(columns="index")
registry

,Наименование / ФИО,Тип субъекта,Категория,ИНН,Основной вид деятельности,Регион,Город,Населенный пункт,Дата включения в реестр,Наличие лицензий,Среднесписочная численность работников за предшествующий календарный год
0,"""КОРПОРАЦИЯ ВИТ"" (ОБЩЕСТВО С ОГРАНИЧЕННОЙ ОТВЕ...",Юридическое лицо,Малое предприятие,5038038838,41.20 Строительство жилых и нежилых зданий,50 - Московская область,NaN,NaN,01.08.2016,Нет,36
1,"""ХОЗРАСЧЕТНАЯ СТРОИТЕЛЬНО-ТЕХНОЛОГИЧЕСКАЯ ФИРМ...",Юридическое лицо,Среднее предприятие,5027006369,41.20 Строительство жилых и нежилых зданий,50 - Московская область,г Дзержинский,NaN,01.08.2016,Да,201
2,"АКЦИОНЕРНОЕ ОБЩЕСТВО ""777""",Юридическое лицо,Малое предприятие,1414006922,41.20 Строительство жилых и нежилых зданий,77 - г.Москва,NaN,NaN,10.08.2017,Да,35
3,"АКЦИОНЕРНОЕ ОБЩЕСТВО ""АГРОТЕХИМПОРТ""",Юридическое лицо,Малое предприятие,3327332190,41.20 Строительство жилых и нежилых зданий,33 - Владимирская область,г Владимир,NaN,10.08.2022,Да,52
4,"АКЦИОНЕРНОЕ ОБЩЕСТВО ""АКС""",Юридическое лицо,Малое предприятие,7816061297,41.20 Строительство жилых и нежилых зданий,78 - г.Санкт-Петербург,NaN,NaN,10.06.2022,Да,21
...,...,...,...,...,...,...,...,...,...,...,...
209,"АКЦИОНЕРНОЕ ОБЩЕСТВО СТРОИТЕЛЬНАЯ КОМПАНИЯ ""ВО...",Юридическое лицо,Среднее предприятие,6316104945,41.20 Строительство жилых и нежилых зданий,63 - Самарская область,г Самара,NaN,10.08.2017,Да,138
210,"АКЦИОНЕРНОЕ ОБЩЕСТВО СТРОИТЕЛЬНАЯ КОМПАНИЯ ""КО...",Юридическое лицо,Среднее предприятие,7816300957,41.20 Строительство жилых и нежилых зданий,78 - г.Санкт-Петербург,NaN,NaN,10.08.2018,Да,78
211,"АКЦИОНЕРНОЕ ОБЩЕСТВО СТРОИТЕЛЬНАЯ КОМПАНИЯ ""ЮЖ...",Юридическое лицо,Среднее предприятие,4217159611,41.20 Строительство жилых и нежилых зданий,42 - Кемеровская область,г Новокузнецк,NaN,10.07.2023,Да,137
212,"АКЦИОНЕРНОЕ ОБЩЕСТВО СТРОИТЕЛЬНАЯ ФИРМА ""ТВЕРЬ...",Юридическое лицо,Малое предприятие,6905008053,41.20 Строительство жилых и нежилых зданий,69 - Тверская область,г Тверь,NaN,10.08.2017,Да,16
213,АКЦИОНЕРНОЕ ОБЩЕСТВО ТУЛЬСКОЕ МОНТАЖНО-НАЛАДОЧ...,Юридическое лицо,Малое предприятие,7104007243,41.20 Строительство жилых и нежилых зданий,71 - Тульская область,г Тула,NaN,10.08.2017,Нет,20

In [14]:
registry.describe()

,Наименование / ФИО,Тип субъекта,Категория,ИНН,Основной вид деятельности,Регион,Город,Населенный пункт,Дата включения в реестр,Наличие лицензий,Среднесписочная численность работников за предшествующий календарный год
count,214,214,214,214,214,214,119,19,214,214,208
unique,213,1,2,214,1,56,76,19,29,2,99
top,"АКЦИОНЕРНОЕ ОБЩЕСТВО ""СТРОИТЕЛЬ""",Юридическое лицо,Малое предприятие,5038038838,41.20 Строительство жилых и нежилых зданий,77 - г.Москва,г Краснодар,с Магарамкент,10.08.2017,Да,29
freq,2,214,163,1,214,50,4,1,134,124,7

In [15]:
registry.drop(columns=["Тип субъекта", "Основной вид деятельности"], inplace=True)
registry.to_csv("datasets/ClearedRegistry.csv")